<?php
/**
 * @file
 *
 * Custom module that alters forms.
 **/

/**
 * Implements hook_form_FORM_ID_alter().
 **/
function altermodule_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // Code to alter form or form state here
  $form['site_phone'] = array(
    '#type' => 'tel',
    '#title' => t('Site Phone'),
    '#default_value' => Drupal::config('system.site')->get('phone'),
  );

  $form['#submit'] [] = 'altermodule_system_site_information_phone_submit';
}

/**
 * Form callback to save site_phone
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 **/
function altermodule_system_site_information_phone_submit(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $config = Drupal::configFactory()->getEditable('system.site');
  $config->set('phone', $form_state->getValue('site_phone'))->save();
}