<?php
/**
 * Implements hook_block_alter().
 **/
function copyright_block_alter(&$definitions) {
  $definitions['user_login_block']['admin_label'] = t('Login');
}

/**
 * Implements hook_block_build_alter().
 **/
 function hook_block_build_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
   // Add the 'url' cache the block per URL.
   if($block->getBaseId() == 'myblock') {
     $build['#contexts'][] = 'url';
   }
 }

/**
 * Implements hook_block_view_alter().
 **/
function hook_block_view_alter(array &$build, \Drupal\Core\Block\
  BlockPluginInterface $block) {
    // Remove the contextual links on all blocks that provide them.
    if (isset($build['#contextual_links'])) {
      unset($build['#contextual_links']);
    }
  }